//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的�?
//
//    手动更改此文件可能会导致应用程序中发生异常行为�?
//    如果重新生成代码，则将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public Student()
        {
            this.Course = new HashSet<Course>();
        }

        public long ID { get; set; }
        public string Name { get; set; }
        [Required]
        [Range(10, 99, ErrorMessage = "error")]
        public int Age { get; set; }
        public string Address { get; set; }

        public virtual ICollection<Course> Course { get; set; }
    }
}
